### ISSUE TITLE
Broken image link in header

### ISSUE THREAD

**Issue by regiseloi-idlab** [DTLab-LabCN/DTT-mDL-Testing#1]
`https://github.com/DTLab-LabCN/DTT-mDL-Testing/blob/main/src/pages/header/Header.tsx` points to `../../images/NB.png`. The actual file name is `Nb.png`.
We'll end up changing this, but right now this needs to be fixed for the build to complete successfully I think.

**Comment by NimeshNB** [comment]
Hi @regiseloi-idlab i have pushed updated code with fixes
