### ISSUE TITLE
UX - step 7 - don't use default values for test results

### ISSUE THREAD

**Issue by regiseloi-idlab** [DTLab-LabCN/DTT-mDL-Testing#12]
For example, the namespace should not default to `org.iso.18013.5.1.mDL` when there was no data retrieved. 
![image](https://github.com/user-attachments/assets/8e9a217c-9b3e-4a2a-a375-21409d527138)
https://github.com/DTLab-LabCN/DTT-mDL-Testing/blob/56877a339e8b1b6255ce55f36d54666c2678747f/src/steps-partials/Step7Partial.tsx#L343

Same comment about step 8 and the details that should have been provided on step 1: https://github.com/DTLab-LabCN/DTT-mDL-Testing/blob/56877a339e8b1b6255ce55f36d54666c2678747f/src/steps-partials/Step8Partial.tsx#L113

**Comment by pruneau628** [comment]
Here is the corrected behavior:

![image](https://github.com/user-attachments/assets/8ccd80e4-adf5-46a2-b01e-a7de0e59acb2)
