### ISSUE TITLE
UX-ish enhancement - step 0 - check for camera permission?

### ISSUE THREAD

**Issue by regiseloi-idlab** [DTLab-LabCN/DTT-mDL-Testing#8]
Logging this one to get people's thoughts:
By "step 0" I mean the "Run a system check before getting started" screen. That works well, and does it what it says (for example, is there a webcam?).
However, for step 2, before we scan the QR code, we have a `checkCameraPermission` function to check that the camera is available to use. Shouldn't we run this check at the beginning? It feels like it would be easier to explain in one place that what follows is going to require access to their camera and bluetooth connection, check it, and then let them proceed.

For clarity, I don't suggest removing the code from step 2, it's fine to leave it there as a precaution. But I think it might be better to check that at the beginning right after the system requirement (and on the same screen, as 1 action from a user perspective).

Additionally, is there a way to check that this feature flag is enabled in Chrome?
`chrome://flags/#enable-experimental-web-platform-features`

**Comment by NimeshNB** [comment]
Yes i'll add  ```checkCameraPermission``` "on step0" where system check is run

For this ```chrome://flags/#enable-experimental-web-platform-features``` 
there is no direct API to access Chrome's internal flags programmatically from a web page due to security and privacy reasons. However, we can detect the availability of specific features enabled by that flag by checking for the related APIs

**Comment by pruneau628** [comment]
For instance, when disabling the `chrome://flags/#enable-experimental-web-platform-features`, and camera access, I get this: 

![image](https://github.com/user-attachments/assets/c3f87b7a-0293-4049-9355-bbe7a02fc374)
