### ISSUE TITLE
UX - step 5 - tooltip content

### ISSUE THREAD

**Issue by regiseloi-idlab** [DTLab-LabCN/DTT-mDL-Testing#9]
This tooltip text is fine for step 4, but for step 5 we need something brief that explains what the role of the verifier certificate is.
Current help text:
![image](https://github.com/user-attachments/assets/705addce-dfa1-4108-906c-4c36cede180f)

**Comment by pruneau628** [comment]
@regiseloi-idlab the tooltip has changed:
![image](https://github.com/user-attachments/assets/d1d43904-9e07-46b6-9824-97e769557ca8)

Please advise.
